### PR TITLE
WIP  Result type

### LINKED ISSUE #16: Implement support for the Result type
The idea is for the c function to return a pointer to a c struct that has a tag and a pointer.  The semantics of the pointer depends on   the value of the tag. We can probably flatten out the constructors for the error type too. 

e.g. for `Result IntersectionError (List Intersection)`

* tag 0 and  pointer to  `List Intersection` for `Ok`
* tag 1 and pointer to `List (Domain, Domain, Sign)`  for `CurvesOverlap`
* tag 2 and null pointer for  `TangentIntersectionAtDegeneratePoint`

In python, we define the result as something like this:

```
class RESULT(Structure):
    _fields_ = [("tag", c_int8), ("ptr", c_void_p)]
lib.fn.restype  = POINTER(RESULT)
```

And add the code that take the response and then

* looks at a value of the tag, and if it is zero - returns the result pointer wrapped in the successful class 
* if it is > 0, then it constructs the right exception for the error and raises it.

### PR DESCRIPTION
**Pull request by w0rm**
Closes #16

### CODE REVIEW

File: opensolid-python/src/Main.hs [hunk 1]
```diff
@@ -70,6 +72,14 @@ setup =
...
         , "        global_tolerance = saved_tolerance"
         ]
+    , unlines
+        [ "class RESULT(Structure):"
+        , "    _fields_ = [('ptr', c_void_p), ('tag', c_int8)]"
+        ]
+    , unlines
+        [ "class IsZero(Exception):"
+        , "    pass"
+        ]
```
Comment (ianmackenzie) [inline opensolid-python/src/Main.hs:82]: Definitely seems a bit TODO-y to have the `IsZero` class harcoded into Python 😅

File: opensolid-api/src/Internal.hs [hunk 2]
```diff
@@ -206,6 +214,12 @@ ffiArgInfo typ = do
         )
 
 ffiReturnInfo :: TH.Exp -> TH.Type -> Codegen (TH.Exp, TH.Type)
+ffiReturnInfo expr (TH.AppT (TH.AppT (TH.ConT containerTyp) errName) nestedTyp)
+  | containerTyp == ''Result = do
```
Comment (ianmackenzie) [inline opensolid-api/src/Internal.hs]: Isn't `containerTyp` actually a `Name` here, not a `Type`?

File: opensolid-api/src/Internal.hs [hunk 3]
```diff
@@ -257,6 +277,29 @@ newPtr val = Prelude.do
 derefPtr :: Foreign.Ptr () -> IO a
 derefPtr = Foreign.castPtrToStablePtr >> Foreign.deRefStablePtr
 
+class (ErrorMessage error) => TaggedError error where
+  fromTaggedPtr :: Foreign.Word8 -> Foreign.Ptr () -> IO error
+  toTaggedPtr :: error -> IO (Foreign.Word8, Foreign.Ptr ())
+
+instance (TaggedError error) => Storable (Result error sucess) where
```
Comment (ianmackenzie) [inline opensolid-api/src/Internal.hs]:
```suggestion
instance (TaggedError error) => Storable (Result error success) where
```

File: opensolid-api/src/Internal.hs [hunk 4]
```diff
@@ -257,6 +277,29 @@ newPtr val = Prelude.do
...
+  sizeOf _ = Foreign.sizeOf (Prelude.undefined :: Foreign.Ptr ()) + (1 :: Int) -- size of a pointer + 1 byte for the tag
```
Comment (ianmackenzie) [inline opensolid-api/src/Internal.hs]: Seems like it could be worth splitting out a top-level constant like

```haskell
pointerSize :: Int
pointerSize =
    Foreign.sizeOf (Prelude.undefined :: Foreign.Ptr ())
```

although I don't think you even need the `Prelude.undefined` business...this seems to work:

```haskell
pointerSize :: Int
pointerSize = Foreign.sizeOf Foreign.nullPtr
```

File: opensolid-api/src/Internal.hs [hunk 5]
```diff
@@ -257,6 +277,29 @@ newPtr val = Prelude.do
...
+    tag <- Foreign.peekByteOff ptr $ Foreign.sizeOf (Prelude.undefined :: Foreign.Ptr ())
+    case tag of
+      (0 :: Foreign.Word8) -> Ok Prelude.<$> Foreign.deRefStablePtr (Foreign.castPtrToStablePtr voidPtr)
+      _ -> Error Prelude.<$> fromTaggedPtr tag voidPtr
+  poke ptr (Error err) = Prelude.do
+    (tag, errPtr) <- toTaggedPtr err
+    Foreign.poke (Foreign.castPtr ptr) errPtr
+    Foreign.pokeByteOff ptr (Foreign.sizeOf (Prelude.undefined :: Foreign.Ptr ())) tag
+  poke ptr (Ok success) = Prelude.do
+    -- TODO: is this a good idea to allocate a stable ptr here?
```
Comment (ianmackenzie) [inline opensolid-api/src/Internal.hs]: I think it's OK...what kinds of issues were you concerned about?

File: opensolid-api/src/Internal.hs [hunk 6]
```diff
@@ -257,6 +277,29 @@ newPtr val = Prelude.do
 derefPtr :: Foreign.Ptr () -> IO a
 derefPtr = Foreign.castPtrToStablePtr >> Foreign.deRefStablePtr
 
+class (ErrorMessage error) => TaggedError error where
+  fromTaggedPtr :: Foreign.Word8 -> Foreign.Ptr () -> IO error
```
Comment (ianmackenzie) [inline opensolid-api/src/Internal.hs:281]: I kinda wonder if in some crazy cases like reading STEP files we might have more than 255 error cases 😅 I'm kinda tempted just to use `Int` instead of `Word8`, since I don't think it's useful to save a few bytes here and there (every FFI call involves allocating a 1.5kb stack anyways...), and then we might not need the `fromInteger` import tricks 😛

File: opensolid-python/src/Main.hs (hunk 1 above)
Comment (w0rm) [reply opensolid-python/src/Main.hs:82]: Yeah everything is hardcoded. In case of this, I wanted to discuss what's the best place for such declarations before implementing the codegen. 

I've noticed that there can be error type declarations with the same names, so probably we should move this class under the module class `Direction2d` and refer to it as `Direction2d.IsZero`.

File: opensolid-api/src/Internal.hs (hunk 5 above)
Comment (w0rm) [reply opensolid-api/src/Internal.hs]: I mean the fact that there is a hidden allocation here. But I don't know how to solve it the other way.

File: opensolid-api/src/Internal.hs (hunk 2 above)
Comment (w0rm) [reply opensolid-api/src/Internal.hs]: Yeah it's a name

File: opensolid-api/src/Internal.hs (hunk 6 above)
Comment (w0rm) [reply opensolid-api/src/Internal.hs:281]: It looks like the size of Haskell `Int` [is defined as a size of void pointer](https://gitlab.haskell.org/HPCohen/ghc/-/blob/master/includes/MachDeps.h#L58), I wonder how can we keep it in sync with the python code. Perhaps we would still need to use something like `Word16`.

File: opensolid-python/src/Main.hs (hunk 1 above)
Comment (ianmackenzie) [reply opensolid-python/src/Main.hs:82]: Yeah a nested class makes sense I think!
